import React, { useState, useEffect } from "react";
import { Search } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { 
  CommandDialog, 
  CommandEmpty, 
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList
} from "@/components/ui/command";
import { useNavigate } from "react-router-dom";

type SearchResult = {
  id: string;
  title: string;
  path: string;
  description?: string;
};

const staticRoutes: SearchResult[] = [
  // Auto-generated Current Conversions
{ id: "a-to-ma", title: "Ampere to Milliampere", path: "/convertor/current?from=a&to=ma" },
{ id: "a-to-ka", title: "Ampere to Kiloampere", path: "/convertor/current?from=a&to=ka" },
{ id: "ma-to-a", title: "Milliampere to Ampere", path: "/convertor/current?from=ma&to=a" },
{ id: "ma-to-ka", title: "Milliampere to Kiloampere", path: "/convertor/current?from=ma&to=ka" },
{ id: "ka-to-a", title: "Kiloampere to Ampere", path: "/convertor/current?from=ka&to=a" },
{ id: "ka-to-ma", title: "Kiloampere to Milliampere", path: "/convertor/current?from=ka&to=ma" },

// Power Conversions
{ id: "w-to-kw", title: "Watt to Kilowatt", path: "/convertor/power?from=w&to=kw" },
{ id: "w-to-hp", title: "Watt to Horsepower", path: "/convertor/power?from=w&to=hp" },
{ id: "kw-to-w", title: "Kilowatt to Watt", path: "/convertor/power?from=kw&to=w" },
{ id: "kw-to-hp", title: "Kilowatt to Horsepower", path: "/convertor/power?from=kw&to=hp" },
{ id: "hp-to-w", title: "Horsepower to Watt", path: "/convertor/power?from=hp&to=w" },
{ id: "hp-to-kw", title: "Horsepower to Kilowatt", path: "/convertor/power?from=hp&to=kw" },

// Voltage Conversions
{ id: "v-to-mv", title: "Volt to Millivolt", path: "/convertor/voltage?from=v&to=mv" },
{ id: "v-to-kv", title: "Volt to Kilovolt", path: "/convertor/voltage?from=v&to=kv" },
{ id: "mv-to-v", title: "Millivolt to Volt", path: "/convertor/voltage?from=mv&to=v" },
{ id: "mv-to-kv", title: "Millivolt to Kilovolt", path: "/convertor/voltage?from=mv&to=kv" },
{ id: "kv-to-v", title: "Kilovolt to Volt", path: "/convertor/voltage?from=kv&to=v" },
{ id: "kv-to-mv", title: "Kilovolt to Millivolt", path: "/convertor/voltage?from=kv&to=mv" },

// Length Conversions (only a subset due to size)
{ id: "m-to-cm", title: "Meter to Centimeter", path: "/convertor/length?from=m&to=cm" },
{ id: "m-to-km", title: "Meter to Kilometer", path: "/convertor/length?from=m&to=km" },
{ id: "cm-to-mm", title: "Centimeter to Millimeter", path: "/convertor/length?from=cm&to=mm" },
{ id: "km-to-mi", title: "Kilometer to Mile", path: "/convertor/length?from=km&to=mi" },
{ id: "ft-to-in", title: "Foot to Inch", path: "/convertor/length?from=ft&to=in" },
// (you can request full length combinations if needed)

// Mass Conversions (subset)
{ id: "g-to-kg", title: "Gram to Kilogram", path: "/convertor/mass?from=g&to=kg" },
{ id: "kg-to-mg", title: "Kilogram to Milligram", path: "/convertor/mass?from=kg&to=mg" },
{ id: "lb-to-oz", title: "Pound to Ounce", path: "/convertor/mass?from=lb&to=oz" },
{ id: "oz-to-g", title: "Ounce to Gram", path: "/convertor/mass?from=oz&to=g" },

// Time Conversions (subset)
{ id: "s-to-ms", title: "Second to Millisecond", path: "/convertor/time?from=s&to=ms" },
{ id: "min-to-s", title: "Minute to Second", path: "/convertor/time?from=min&to=s" },
{ id: "h-to-min", title: "Hour to Minute", path: "/convertor/time?from=h&to=min" },
{ id: "d-to-h", title: "Day to Hour", path: "/convertor/time?from=d&to=h" },
{ id: "ms-to-s", title: "Millisecond to Second", path: "/convertor/time?from=ms&to=s" },

  { id: "home", title: "Home", path: "/" },
  { id: "test", title: "Test", path: "/test" },
  { id: "scientific", title: "Scientific", path: "/scientific" },
  { id: "percentage", title: "Percentage", path: "/percentage" },
  { id: "fraction", title: "Fraction", path: "/fraction" },
  { id: "average", title: "Average", path: "/average" },
  { id: "grade", title: "Grade", path: "/grade" },
  { id: "gpa", title: "Gpa", path: "/gpa" },
  { id: "final-grade", title: "Final Grade", path: "/final-grade" },
  { id: "mortgage", title: "Mortgage", path: "/mortgage" },
  { id: "compound-interest", title: "Compound Interest", path: "/compound-interest" },
  { id: "bmi", title: "Bmi", path: "/bmi" },
  { id: "unit-converter", title: "Unit Converter Converter", path: "/unit-converter" },
  { id: "convertor-length", title: "Length Converter", path: "/convertor/length" },
  { id: "convertor-mass", title: "Mass Converter", path: "/convertor/mass" },
  { id: "convertor-temperature", title: "Temperature Converter", path: "/convertor/temperature" },
  { id: "convertor-area", title: "Area Converter", path: "/convertor/area" },
  { id: "convertor-volume", title: "Volume Converter", path: "/convertor/volume" },
  { id: "convertor-time", title: "Time Converter", path: "/convertor/time" },
  { id: "convertor-speed", title: "Speed Converter", path: "/convertor/speed" },
  { id: "convertor-pressure", title: "Pressure Converter", path: "/convertor/pressure" },
  { id: "convertor-energy", title: "Energy Converter", path: "/convertor/energy" },
  { id: "convertor-power", title: "Power Converter", path: "/convertor/power" },
  { id: "convertor-data", title: "Data Converter", path: "/convertor/data" },
  { id: "convertor-angle", title: "Angle Converter", path: "/convertor/angle" },
  { id: "convertor-frequency", title: "Frequency Converter", path: "/convertor/frequency" },
  { id: "convertor-fuel_economy", title: "Fuel Economy Converter", path: "/convertor/fuel_economy" },
  { id: "convertor-voltage", title: "Voltage Converter", path: "/convertor/voltage" },
  { id: "convertor-current", title: "Current Converter", path: "/convertor/current" },
  { id: "convertor-color", title: "Color Converter", path: "/convertor/color" },
  { id: "electrical-basic-terms", title: "Basic Terms", path: "/electrical/basic-terms" },
  { id: "electrical-calculators-ohms-law", title: "Ohms Law Calculator", path: "/electrical/calculators/ohms-law" },
  { id: "electrical-units", title: "Units", path: "/electrical/units" },
  { id: "electrical-components", title: "Components", path: "/electrical/components" },
  { id: "electrical-symbols", title: "Symbols", path: "/electrical/symbols" },
  { id: "electrical-laws", title: "Laws", path: "/electrical/laws" },
  { id: "electrical-save-electricity", title: "Save Electricity", path: "/electrical/save-electricity" },
  { id: "electrical-calculators-power", title: "Power Calculator", path: "/electrical/calculators/power" },
  { id: "electrical-calculators-voltage-divider", title: "Voltage Divider Calculator", path: "/electrical/calculators/voltage-divider" },
  { id: "electrical-calculators-capacitance", title: "Capacitance Calculator", path: "/electrical/calculators/capacitance" },
  { id: "electrical-calculators-resistance", title: "Resistance Calculator", path: "/electrical/calculators/resistance" },
  { id: "electrical-calculators-frequency", title: "Frequency Calculator", path: "/electrical/calculators/frequency" },
  { id: "electrical-lighting-lumens", title: "Lumens", path: "/electrical/lighting/lumens" },
  { id: "electrical-lighting-led-savings", title: "Led Savings", path: "/electrical/lighting/led-savings" },
  { id: "electrical-lighting-wattage", title: "Wattage", path: "/electrical/lighting/wattage" },
  { id: "electrical-lighting-color-temp", title: "Color Temp", path: "/electrical/lighting/color-temp" },
  { id: "electrical-lighting-energy-usage", title: "Energy Usage", path: "/electrical/lighting/energy-usage" },
  { id: "electrical-units-ampere", title: "Ampere", path: "/electrical/units/ampere" },
  { id: "electrical-units-dbm", title: "Dbm", path: "/electrical/units/dbm" },
  { id: "electrical-units-dbw", title: "Dbw", path: "/electrical/units/dbw" },
  { id: "electrical-units-decibel", title: "Decibel", path: "/electrical/units/decibel" },
  { id: "electrical-units-farad", title: "Farad", path: "/electrical/units/farad" },
  { id: "electrical-units-kva", title: "Kva", path: "/electrical/units/kva" },
  { id: "electrical-units-kw", title: "Kw", path: "/electrical/units/kw" },
  { id: "electrical-units-kwh", title: "Kwh", path: "/electrical/units/kwh" },
  { id: "electrical-units-ohm", title: "Ohm", path: "/electrical/units/ohm" },
  { id: "electrical-units-volt", title: "Volt", path: "/electrical/units/volt" },
  { id: "electrical-units-watt", title: "Watt", path: "/electrical/units/watt" },
  { id: "electrical-components-resistor", title: "Resistor", path: "/electrical/components/resistor" },
  { id: "electrical-components-capacitor", title: "Capacitor", path: "/electrical/components/capacitor" },
  { id: "electrical-components-inductor", title: "Inductor", path: "/electrical/components/inductor" },
  { id: "electrical-components-dip-switch", title: "Dip Switch", path: "/electrical/components/dip-switch" },
  { id: "electrical-components-solder-bridge", title: "Solder Bridge", path: "/electrical/components/solder-bridge" },
  { id: "electrical-content-voltage", title: "Voltage", path: "/electrical/content/voltage" },
  { id: "electrical-content-resistance", title: "Resistance", path: "/electrical/content/resistance" },
  { id: "electrical-content-current", title: "Current", path: "/electrical/content/current" },
  { id: "electrical-content-power", title: "Power", path: "/electrical/content/power" },
  { id: "electrical-content-charge", title: "Charge", path: "/electrical/content/charge" },
  { id: "electrical-content-efficiency", title: "Efficiency", path: "/electrical/content/efficiency" },
  { id: "electrical-content-factor", title: "Factor", path: "/electrical/content/factor" },
  { id: "electrical-symbols-switch", title: "Switch", path: "/electrical/symbols/switch" },
  { id: "electrical-symbols-ground", title: "Ground", path: "/electrical/symbols/ground" },
  { id: "electrical-symbols-resistor", title: "Resistor", path: "/electrical/symbols/resistor" },
  { id: "electrical-symbols-capacitor", title: "Capacitor", path: "/electrical/symbols/capacitor" },
  { id: "electrical-symbols-diode", title: "Diode", path: "/electrical/symbols/diode" },
  { id: "electrical-symbols-transistor", title: "Transistor", path: "/electrical/symbols/transistor" },
  { id: "electrical-circuit-laws-ohm", title: "Ohm", path: "/electrical/circuit-laws/ohm" },
  { id: "electrical-circuit-laws-voltage-divider", title: "Voltage Divider", path: "/electrical/circuit-laws/voltage-divider" },
  { id: "electrical-circuit-laws-kirchhoff", title: "Kirchhoff", path: "/electrical/circuit-laws/kirchhoff" },
  { id: "electrical-circuit-laws-coulomb", title: "Coulomb", path: "/electrical/circuit-laws/coulomb" },
  { id: "howto-save-electricity", title: "Save Electricity", path: "/howto/save-electricity" },
  { id: "howto-save-energy", title: "Save Energy", path: "/howto/save-energy" },
  { id: "electrical-calculations", title: "Electrical Calculations", path: "/electrical-calculations" },
  { id: "calculations-:slug", title: ":Slug", path: "/calculations/:slug" },
  { id: "convertor-electrical-:slug", title: ":Slug Converter", path: "/convertor-electrical/:slug" },
  { id: "electrical-calculators", title: "Electrical Calculators Calculator", path: "/electrical-calculators" },
  { id: "electrical-calculators-amps-to-kw-calculator", title: "Amps To Kw Calculator Calculator", path: "/electrical-calculators/amps-to-kw-calculator" },
  { id: "electrical-calculators-amps-to-kva-calculator", title: "Amps To Kva Calculator Calculator", path: "/electrical-calculators/amps-to-kva-calculator" },
  { id: "electrical-calculators-amps-to-va-calculator", title: "Amps To Va Calculator Calculator", path: "/electrical-calculators/amps-to-va-calculator" },
  { id: "electrical-calculators-amps-to-volts-calculator", title: "Amps To Volts Calculator Calculator", path: "/electrical-calculators/amps-to-volts-calculator" },
  { id: "electrical-calculators-amps-to-watts-calculator", title: "Amps To Watts Calculator Calculator", path: "/electrical-calculators/amps-to-watts-calculator" },
  { id: "electrical-calculators-electricity-bill-calculator", title: "Electricity Bill Calculator Calculator", path: "/electrical-calculators/electricity-bill-calculator" },
  { id: "electrical-calculators-energy-consumption-calculator", title: "Energy Consumption Calculator Calculator", path: "/electrical-calculators/energy-consumption-calculator" },
  { id: "electrical-calculators-energy-cost-calculator", title: "Energy Cost Calculator Calculator", path: "/electrical-calculators/energy-cost-calculator" },
  { id: "electrical-calculators-ev-to-volts-calculator", title: "Ev To Volts Calculator Calculator", path: "/electrical-calculators/ev-to-volts-calculator" },
  { id: "electrical-calculators-joules-to-volts-calculator", title: "Joules To Volts Calculator Calculator", path: "/electrical-calculators/joules-to-volts-calculator" },
  { id: "electrical-calculators-joules-to-watts-calculator", title: "Joules To Watts Calculator Calculator", path: "/electrical-calculators/joules-to-watts-calculator" },
  { id: "electrical-calculators-kva-to-amps-calculator", title: "Kva To Amps Calculator Calculator", path: "/electrical-calculators/kva-to-amps-calculator" },
  { id: "electrical-calculators-kva-to-watts-calculator", title: "Kva To Watts Calculator Calculator", path: "/electrical-calculators/kva-to-watts-calculator" },
  { id: "electrical-calculators-kva-to-kw-calculator", title: "Kva To Kw Calculator Calculator", path: "/electrical-calculators/kva-to-kw-calculator" },
  { id: "electrical-calculators-kva-to-va-calculator", title: "Kva To Va Calculator Calculator", path: "/electrical-calculators/kva-to-va-calculator" },
  { id: "electrical-calculators-kw-to-amps-calculator", title: "Kw To Amps Calculator Calculator", path: "/electrical-calculators/kw-to-amps-calculator" },
  { id: "electrical-calculators-kw-to-volts-calculator", title: "Kw To Volts Calculator Calculator", path: "/electrical-calculators/kw-to-volts-calculator" },
  { id: "electrical-calculators-kw-to-kwh-calculator", title: "Kw To Kwh Calculator Calculator", path: "/electrical-calculators/kw-to-kwh-calculator" },
  { id: "electrical-calculators-kw-to-va-calculator", title: "Kw To Va Calculator Calculator", path: "/electrical-calculators/kw-to-va-calculator" },
  { id: "electrical-calculators-kw-to-kva-calculator", title: "Kw To Kva Calculator Calculator", path: "/electrical-calculators/kw-to-kva-calculator" },
  { id: "electrical-calculators-kwh-to-kw-calculator", title: "Kwh To Kw Calculator Calculator", path: "/electrical-calculators/kwh-to-kw-calculator" },
  { id: "electrical-calculators-kwh-to-watts-calculator", title: "Kwh To Watts Calculator Calculator", path: "/electrical-calculators/kwh-to-watts-calculator" },
  { id: "electrical-calculators-mah-to-wh-calculator", title: "Mah To Wh Calculator Calculator", path: "/electrical-calculators/mah-to-wh-calculator" },
  { id: "electrical-calculators-ohms-law-calculator", title: "Ohms Law Calculator Calculator", path: "/electrical-calculators/ohms-law-calculator" },
  { id: "electrical-calculators-power-calculator", title: "Power Calculator Calculator", path: "/electrical-calculators/power-calculator" },
  { id: "electrical-calculators-power-factor-calculator", title: "Power Factor Calculator Calculator", path: "/electrical-calculators/power-factor-calculator" },
  { id: "electrical-calculators-voltage-divider-calculator", title: "Voltage Divider Calculator Calculator", path: "/electrical-calculators/voltage-divider-calculator" },
  { id: "electrical-calculators-va-to-amps-calculator", title: "Va To Amps Calculator Calculator", path: "/electrical-calculators/va-to-amps-calculator" },
  { id: "electrical-calculators-va-to-watts-calculator", title: "Va To Watts Calculator Calculator", path: "/electrical-calculators/va-to-watts-calculator" },
  { id: "electrical-calculators-va-to-kw-calculator", title: "Va To Kw Calculator Calculator", path: "/electrical-calculators/va-to-kw-calculator" },
  { id: "electrical-calculators-va-to-kva-calculator", title: "Va To Kva Calculator Calculator", path: "/electrical-calculators/va-to-kva-calculator" },
  { id: "electrical-calculators-voltage-drop-calculator", title: "Voltage Drop Calculator Calculator", path: "/electrical-calculators/voltage-drop-calculator" },
  { id: "electrical-calculators-volts-to-amps-calculator", title: "Volts To Amps Calculator Calculator", path: "/electrical-calculators/volts-to-amps-calculator" },
  { id: "electrical-calculators-volts-to-watts-calculator", title: "Volts To Watts Calculator Calculator", path: "/electrical-calculators/volts-to-watts-calculator" },
  { id: "electrical-calculators-volts-to-kw-calculator", title: "Volts To Kw Calculator Calculator", path: "/electrical-calculators/volts-to-kw-calculator" },
  { id: "electrical-calculators-volts-to-joules-calculator", title: "Volts To Joules Calculator Calculator", path: "/electrical-calculators/volts-to-joules-calculator" },
  { id: "electrical-calculators-volts-to-ev-calculator", title: "Volts To Ev Calculator Calculator", path: "/electrical-calculators/volts-to-ev-calculator" },
  { id: "electrical-calculators-watts-volts-amps-ohms-calculator", title: "Watts Volts Amps Ohms Calculator Calculator", path: "/electrical-calculators/watts-volts-amps-ohms-calculator" },
  { id: "electrical-calculators-watts-to-amps-calculator", title: "Watts To Amps Calculator Calculator", path: "/electrical-calculators/watts-to-amps-calculator" },
  { id: "electrical-calculators-watts-to-kwh-calculator", title: "Watts To Kwh Calculator Calculator", path: "/electrical-calculators/watts-to-kwh-calculator" },
  { id: "electrical-calculators-watts-to-volts-calculator", title: "Watts To Volts Calculator Calculator", path: "/electrical-calculators/watts-to-volts-calculator" },
  { id: "electrical-calculators-watts-to-va-calculator", title: "Watts To Va Calculator Calculator", path: "/electrical-calculators/watts-to-va-calculator" },
  { id: "electrical-calculators-watts-to-kva-calculator", title: "Watts To Kva Calculator Calculator", path: "/electrical-calculators/watts-to-kva-calculator" },
  { id: "electrical-calculators-watts-to-joules-calculator", title: "Watts To Joules Calculator Calculator", path: "/electrical-calculators/watts-to-joules-calculator" },
  { id: "electrical-calculators-wh-to-mah-calculator", title: "Wh To Mah Calculator Calculator", path: "/electrical-calculators/wh-to-mah-calculator" },
  { id: "electrical-calculators-wire-gauge-calculator", title: "Wire Gauge Calculator Calculator", path: "/electrical-calculators/wire-gauge-calculator" },
  { id: "lighting-calculators", title: "Lighting Calculators Calculator", path: "/lighting-calculators" },
  { id: "lighting-calculators-candela-to-lumens-calculator", title: "Candela To Lumens Calculator Calculator", path: "/lighting-calculators/candela-to-lumens-calculator" },
  { id: "lighting-calculators-candela-to-lux-calculator", title: "Candela To Lux Calculator Calculator", path: "/lighting-calculators/candela-to-lux-calculator" },
  { id: "lighting-calculators-footcandles-to-lux-calculator", title: "Footcandles To Lux Calculator Calculator", path: "/lighting-calculators/footcandles-to-lux-calculator" },
  { id: "lighting-calculators-lumens-to-candela-calculator", title: "Lumens To Candela Calculator Calculator", path: "/lighting-calculators/lumens-to-candela-calculator" },
  { id: "lighting-calculators-lumens-to-lux-calculator", title: "Lumens To Lux Calculator Calculator", path: "/lighting-calculators/lumens-to-lux-calculator" },
  { id: "lighting-calculators-lumens-to-millicandela-calculator", title: "Lumens To Millicandela Calculator Calculator", path: "/lighting-calculators/lumens-to-millicandela-calculator" },
  { id: "lighting-calculators-lumens-to-watts-calculator", title: "Lumens To Watts Calculator Calculator", path: "/lighting-calculators/lumens-to-watts-calculator" },
  { id: "lighting-calculators-lux-to-candela-calculator", title: "Lux To Candela Calculator Calculator", path: "/lighting-calculators/lux-to-candela-calculator" },
  { id: "lighting-calculators-lux-to-footcandles-calculator", title: "Lux To Footcandles Calculator Calculator", path: "/lighting-calculators/lux-to-footcandles-calculator" },
  { id: "lighting-calculators-lux-to-lumens-calculator", title: "Lux To Lumens Calculator Calculator", path: "/lighting-calculators/lux-to-lumens-calculator" },
  { id: "lighting-calculators-lux-to-watts-calculator", title: "Lux To Watts Calculator Calculator", path: "/lighting-calculators/lux-to-watts-calculator" },
  { id: "lighting-calculators-millicandela-to-lumens-calculator", title: "Millicandela To Lumens Calculator Calculator", path: "/lighting-calculators/millicandela-to-lumens-calculator" },
  { id: "lighting-calculators-watts-to-lumens-calculator", title: "Watts To Lumens Calculator Calculator", path: "/lighting-calculators/watts-to-lumens-calculator" },
  { id: "lighting-calculators-watts-to-lux-calculator", title: "Watts To Lux Calculator Calculator", path: "/lighting-calculators/watts-to-lux-calculator" },
  { id: "all-calculators", title: "All Calculators Calculator", path: "/all-calculators" },
  { id: "all-conversions", title: "All Conversions", path: "/all-conversions" },
  { id: "finance-all", title: "Finance All", path: "/finance-all" },
  { id: "convertor-number", title: "Number Converter", path: "/convertor/number" },
  { id: "calculator-discount", title: "Discount Calculator", path: "/calculator/discount" },
  { id: "calculator-effective-interest-rate", title: "Effective Interest Rate Calculator", path: "/calculator/effective-interest-rate" },
  { id: "calculator-gst", title: "Gst Calculator", path: "/calculator/gst" },
  { id: "calculator-simple-interest", title: "Simple Interest Calculator", path: "/calculator/simple-interest" },
  { id: "calculator-vat", title: "Vat Calculator", path: "/calculator/vat" },
  { id: "calculator-percentage-change", title: "Percentage Change Calculator", path: "/calculator/percentage-change" },
  { id: "calculator-percentage-increase", title: "Percentage Increase Calculator", path: "/calculator/percentage-increase" },
  { id: "tools-adding-fractions-calculator", title: "Adding Fractions Calculator Calculator", path: "/tools/adding-fractions-calculator" },
  { id: "tools-addition-calculator", title: "Addition Calculator Calculator", path: "/tools/addition-calculator" },
  { id: "tools-antilog-calculator", title: "Antilog Calculator Calculator", path: "/tools/antilog-calculator" },
  { id: "tools-arccos-calculator", title: "Arccos Calculator Calculator", path: "/tools/arccos-calculator" },
  { id: "tools-arcsin-calculator", title: "Arcsin Calculator Calculator", path: "/tools/arcsin-calculator" },
  { id: "tools-arctan-calculator", title: "Arctan Calculator Calculator", path: "/tools/arctan-calculator" },
  { id: "tools-base-calculator", title: "Base Calculator Calculator", path: "/tools/base-calculator" },
  { id: "tools-binary-calculator", title: "Binary Calculator Calculator", path: "/tools/binary-calculator" },
  { id: "tools-complex-numbers-calculator", title: "Complex Numbers Calculator Calculator", path: "/tools/complex-numbers-calculator" },
  { id: "tools-convolution-calculator", title: "Convolution Calculator Calculator", path: "/tools/convolution-calculator" },
  { id: "tools-cosine-calculator", title: "Cosine Calculator Calculator", path: "/tools/cosine-calculator" },
  { id: "tools-dividing-fractions-calculator", title: "Dividing Fractions Calculator Calculator", path: "/tools/dividing-fractions-calculator" },
  { id: "tools-division-calculator", title: "Division Calculator Calculator", path: "/tools/division-calculator" },
  { id: "tools-exponential-growth-calculator", title: "Exponential Growth Calculator Calculator", path: "/tools/exponential-growth-calculator" },
  { id: "tools-exponents-calculator", title: "Exponents Calculator Calculator", path: "/tools/exponents-calculator" },
  { id: "tools-factorial-calculator", title: "Factorial Calculator Calculator", path: "/tools/factorial-calculator" },
  { id: "tools-fractions-calculator", title: "Fractions Calculator Calculator", path: "/tools/fractions-calculator" },
  { id: "tools-fraction-simplifier", title: "Fraction Simplifier Tool", path: "/tools/fraction-simplifier" },
  { id: "tools-gcf-calculator", title: "Gcf Calculator Calculator", path: "/tools/gcf-calculator" },
  { id: "tools-hex-calculator", title: "Hex Calculator Calculator", path: "/tools/hex-calculator" },
  { id: "tools-lcm-calculator", title: "Lcm Calculator Calculator", path: "/tools/lcm-calculator" },
  { id: "tools-ln-calculator", title: "Ln Calculator Calculator", path: "/tools/ln-calculator" },
  { id: "tools-log-calculator", title: "Log Calculator Calculator", path: "/tools/log-calculator" },
  { id: "tools-multiplication-calculator", title: "Multiplication Calculator Calculator", path: "/tools/multiplication-calculator" },
  { id: "tools-multiplying-fractions-calculator", title: "Multiplying Fractions Calculator Calculator", path: "/tools/multiplying-fractions-calculator" },
  { id: "tools-percent-error-calculator", title: "Percent Error Calculator Calculator", path: "/tools/percent-error-calculator" },
  { id: "tools-percentage-increase-calculator", title: "Percentage Increase Calculator Calculator", path: "/tools/percentage-increase-calculator" },
  { id: "tools-pythagorean-theorem-calculator", title: "Pythagorean Theorem Calculator Calculator", path: "/tools/pythagorean-theorem-calculator" },
  { id: "tools-quadratic-equation-solver", title: "Quadratic Equation Solver Tool", path: "/tools/quadratic-equation-solver" },
  { id: "tools-ratio-calculator", title: "Ratio Calculator Calculator", path: "/tools/ratio-calculator" },
  { id: "tools-remainder-calculator", title: "Remainder Calculator Calculator", path: "/tools/remainder-calculator" },
  { id: "tools-right-triangle-calculator", title: "Right Triangle Calculator Calculator", path: "/tools/right-triangle-calculator" },
  { id: "tools-root-calculator", title: "Root Calculator Calculator", path: "/tools/root-calculator" },
  { id: "tools-scientific-notation-calculator", title: "Scientific Notation Calculator Calculator", path: "/tools/scientific-notation-calculator" },
  { id: "tools-simple-math-calculator", title: "Simple Math Calculator Calculator", path: "/tools/simple-math-calculator" },
  { id: "tools-sine-calculator", title: "Sine Calculator Calculator", path: "/tools/sine-calculator" },
  { id: "tools-square-root-calculator", title: "Square Root Calculator Calculator", path: "/tools/square-root-calculator" },
  { id: "tools-standard-deviation-calculator", title: "Standard Deviation Calculator Calculator", path: "/tools/standard-deviation-calculator" },
  { id: "tools-subtracting-fractions-calculator", title: "Subtracting Fractions Calculator Calculator", path: "/tools/subtracting-fractions-calculator" },
  { id: "tools-subtraction-calculator", title: "Subtraction Calculator Calculator", path: "/tools/subtraction-calculator" },
  { id: "tools-tangent-calculator", title: "Tangent Calculator Calculator", path: "/tools/tangent-calculator" },
  { id: "tools-trigonometry-calculator", title: "Trigonometry Calculator Calculator", path: "/tools/trigonometry-calculator" },
  { id: "tools-weighted-average-calculator", title: "Weighted Average Calculator Calculator", path: "/tools/weighted-average-calculator" },
  { id: "tools-variance-calculator", title: "Variance Calculator Calculator", path: "/tools/variance-calculator" },
  { id: "tools-wire-gauge-calculator", title: "Wire Gauge Calculator Calculator", path: "/tools/wire-gauge-calculator" },
  { id: "tools-awg-to-mm-calculator", title: "Awg To Mm Calculator Calculator", path: "/tools/awg-to-mm-calculator" },
  { id: "tools-swg-to-mm-calculator", title: "Swg To Mm Calculator Calculator", path: "/tools/swg-to-mm-calculator" },
  { id: "tools-voltage-drop-calculator", title: "Voltage Drop Calculator Calculator", path: "/tools/voltage-drop-calculator" },
  { id: "tools-2-gauge-wire-calculator", title: "2 Gauge Wire Calculator Calculator", path: "/tools/2-gauge-wire-calculator" },
  { id: "tools-time-now", title: "Time Now Tool", path: "/tools/time-now" },
  { id: "tools-date-calculator", title: "Date Calculator Calculator", path: "/tools/date-calculator" },
  { id: "tools-time-calculator", title: "Time Calculator Calculator", path: "/tools/time-calculator" },
  { id: "tools-age-calculator", title: "Age Calculator Calculator", path: "/tools/age-calculator" },
  { id: "tools-birthday-calculator", title: "Birthday Calculator Calculator", path: "/tools/birthday-calculator" },
  { id: "tools-days-in-year", title: "Days In Year Tool", path: "/tools/days-in-year" },
  { id: "tools-dst-change", title: "Dst Change Tool", path: "/tools/dst-change" },
  { id: "tools-dst-back", title: "Dst Back Tool", path: "/tools/dst-back" },
  { id: "tools-dst-forward", title: "Dst Forward Tool", path: "/tools/dst-forward" },
  { id: "tools-hours-in-week", title: "Hours In Week Tool", path: "/tools/hours-in-week" },
  { id: "tools-hours-in-year", title: "Hours In Year Tool", path: "/tools/hours-in-year" },
  { id: "tools-months-of-year", title: "Months Of Year Tool", path: "/tools/months-of-year" },
  { id: "tools-seconds-in-day", title: "Seconds In Day Tool", path: "/tools/seconds-in-day" },
  { id: "tools-seconds-in-hour", title: "Seconds In Hour Tool", path: "/tools/seconds-in-hour" },
  { id: "tools-seconds-in-year", title: "Seconds In Year Tool", path: "/tools/seconds-in-year" },
  { id: "tools-todays-date", title: "Todays Date Tool", path: "/tools/todays-date" },
  { id: "tools-weeks-in-month", title: "Weeks In Month Tool", path: "/tools/weeks-in-month" },
  { id: "tools-weeks-in-year", title: "Weeks In Year Tool", path: "/tools/weeks-in-year" },
  { id: "tools-current-time", title: "Current Time Tool", path: "/tools/current-time" },
  { id: "eco-reduce-carbon-footprint", title: "Reduce Carbon Footprint", path: "/eco/reduce-carbon-footprint" },
  { id: "eco-reduce-plastic-waste", title: "Reduce Plastic Waste", path: "/eco/reduce-plastic-waste" },
  { id: "eco-save-fuel", title: "Save Fuel", path: "/eco/save-fuel" },
  { id: "eco-save-energy", title: "Save Energy", path: "/eco/save-energy" },
  { id: "eco-green-hosting-comparison", title: "Green Hosting Comparison", path: "/eco/green-hosting-comparison" },
  { id: "eco-plant-trees", title: "Plant Trees", path: "/eco/plant-trees" },
  { id: "eco-save-electricity", title: "Save Electricity", path: "/eco/save-electricity" },
  { id: "mathematics-all", title: "All", path: "/mathematics/all" },
  { id: "mathematics-numbers", title: "Numbers", path: "/mathematics/numbers" },
  { id: "numbers-addition-table", title: "Addition Table", path: "/numbers/addition-table" },
  { id: "numbers-multiplication-table", title: "Multiplication Table", path: "/numbers/multiplication-table" },
  { id: "numbers-exponents-rules", title: "Exponents Rules", path: "/numbers/exponents-rules" },
  { id: "numbers-numeral-systems", title: "Numeral Systems", path: "/numbers/numeral-systems" },
  { id: "numbers-percentage", title: "Percentage", path: "/numbers/percentage" },
  { id: "numbers-per-mille", title: "Per Mille", path: "/numbers/per-mille" },
  { id: "numbers-parts-per-million", title: "Parts Per Million", path: "/numbers/parts-per-million" },
  { id: "numbers-zero", title: "Zero", path: "/numbers/zero" },
  { id: "numbers-prime-number", title: "Prime Number", path: "/numbers/prime-number" },
  { id: "numbers-e-constant", title: "E Constant", path: "/numbers/e-constant" },
  { id: "numbers-fibonacci", title: "Fibonacci", path: "/numbers/fibonacci" },
  { id: "mathematics-algebra", title: "Algebra", path: "/mathematics/algebra" },
  { id: "algebra-factorial", title: "Factorial", path: "/algebra/factorial" },
  { id: "algebra-logarithm", title: "Logarithm", path: "/algebra/logarithm" },
  { id: "algebra-logarithm-rules", title: "Logarithm Rules", path: "/algebra/logarithm-rules" },
  { id: "algebra-natural-logarithm", title: "Natural Logarithm", path: "/algebra/natural-logarithm" },
  { id: "algebra-logarithm-table", title: "Logarithm Table", path: "/algebra/logarithm-table" },
  { id: "algebra-quadratic-equation", title: "Quadratic Equation", path: "/algebra/quadratic-equation" },
  { id: "mathematics-trigonometry", title: "Trigonometry", path: "/mathematics/trigonometry" },
  { id: "trigonometry-arccos", title: "Arccos", path: "/trigonometry/arccos" },
  { id: "trigonometry-arcsin", title: "Arcsin", path: "/trigonometry/arcsin" },
  { id: "trigonometry-arctan", title: "Arctan", path: "/trigonometry/arctan" },
  { id: "mathematics-probability", title: "Probability", path: "/mathematics/probability" },
  { id: "probability-basic", title: "Basic", path: "/probability/basic" },
  { id: "probability-expectation", title: "Expectation", path: "/probability/expectation" },
  { id: "probability-variance", title: "Variance", path: "/probability/variance" },
  { id: "probability-standard-deviation", title: "Standard Deviation", path: "/probability/standard-deviation" },
  { id: "probability-distribution", title: "Distribution", path: "/probability/distribution" },
  { id: "probability-normal-distribution", title: "Normal Distribution", path: "/probability/normal-distribution" },
  { id: "mathematics-calculus", title: "Calculus", path: "/mathematics/calculus" },
  { id: "calculus-derivative", title: "Derivative", path: "/calculus/derivative" },
  { id: "calculus-laplace-transform", title: "Laplace Transform", path: "/calculus/laplace-transform" },
  { id: "calculus-convolution", title: "Convolution", path: "/calculus/convolution" },
  { id: "mathematics-symbols", title: "Symbols", path: "/mathematics/symbols" },
  { id: "symbols-math", title: "Math", path: "/symbols/math" },
  { id: "symbols-algebra", title: "Algebra", path: "/symbols/algebra" },
  { id: "symbols-geometry", title: "Geometry", path: "/symbols/geometry" },
  { id: "symbols-statistics", title: "Statistics", path: "/symbols/statistics" },
  { id: "symbols-logic", title: "Logic", path: "/symbols/logic" },
  { id: "symbols-set-theory", title: "Set Theory", path: "/symbols/set-theory" },
  { id: "symbols-calculus-analysis", title: "Calculus Analysis", path: "/symbols/calculus-analysis" },
  { id: "symbols-numbers", title: "Numbers", path: "/symbols/numbers" },
  { id: "symbols-greek", title: "Greek", path: "/symbols/greek" },
  { id: "symbols-roman-numerals", title: "Roman Numerals", path: "/symbols/roman-numerals" },
  { id: "web-all", title: "All", path: "/web/all" },
  { id: "web-colors", title: "Colors", path: "/web/colors" },
  { id: "tools-web-colors", title: "Web Colors Tool", path: "/tools/web-colors" },
  { id: "tools-color-scheme-generator", title: "Color Scheme Generator Tool", path: "/tools/color-scheme-generator" },
  { id: "tools-html-color-codes", title: "Html Color Codes Tool", path: "/tools/html-color-codes" },
  { id: "tools-rgb-color-picker", title: "Rgb Color Picker Tool", path: "/tools/rgb-color-picker" },
  { id: "tools-web-safe-colors", title: "Web Safe Colors Tool", path: "/tools/web-safe-colors" },
  { id: "web-development", title: "Development", path: "/web/development" },
  { id: "tools-canonical-url-generator", title: "Canonical Url Generator Tool", path: "/tools/canonical-url-generator" },
  { id: "tools-htaccess-redirection", title: "Htaccess Redirection Tool", path: "/tools/htaccess-redirection" },
  { id: "tools-html-redirection", title: "Html Redirection Tool", path: "/tools/html-redirection" },
  { id: "tools-javascript-redirection", title: "Javascript Redirection Tool", path: "/tools/javascript-redirection" },
  { id: "tools-jquery-redirection", title: "Jquery Redirection Tool", path: "/tools/jquery-redirection" },
  { id: "tools-php-redirection", title: "Php Redirection Tool", path: "/tools/php-redirection" },
  { id: "tools-screen-resolution-statistics", title: "Screen Resolution Statistics Tool", path: "/tools/screen-resolution-statistics" },
  { id: "tools-website-traffic-down-checker", title: "Website Traffic Down Checker Tool", path: "/tools/website-traffic-down-checker" },
  { id: "web-html", title: "Html", path: "/web/html" },
  { id: "tools-html-character-codes", title: "Html Character Codes Tool", path: "/tools/html-character-codes" },
  { id: "tools-html-comments-guide", title: "Html Comments Guide Tool", path: "/tools/html-comments-guide" },
  { id: "tools-html-tables-generator", title: "Html Tables Generator Tool", path: "/tools/html-tables-generator" },
  { id: "tools-html-color", title: "Html Color Tool", path: "/tools/html-color" },
  { id: "web-tools", title: "Tools Tool", path: "/web/tools" },
  { id: "code-all", title: "All", path: "/code/all" },
  { id: "linux-all", title: "All", path: "/linux/all" },
  { id: "linux-cat-command", title: "Cat Command", path: "/linux/cat-command" },
  { id: "linux-cd-command", title: "Cd Command", path: "/linux/cd-command" },
  { id: "linux-cp-command", title: "Cp Command", path: "/linux/cp-command" },
  { id: "linux-current-directory", title: "Current Directory", path: "/linux/current-directory" },
  { id: "linux-gcc-command", title: "Gcc Command", path: "/linux/gcc-command" },
  { id: "linux-ls-command", title: "Ls Command", path: "/linux/ls-command" },
  { id: "linux-move-files", title: "Move Files", path: "/linux/move-files" },
  { id: "linux-mv-command", title: "Mv Command", path: "/linux/mv-command" },
  { id: "linux-pwd-command", title: "Pwd Command", path: "/linux/pwd-command" },
  { id: "linux-slow-virtualbox-ubuntu", title: "Slow Virtualbox Ubuntu", path: "/linux/slow-virtualbox-ubuntu" },
  { id: "linux-view-files", title: "View Files", path: "/linux/view-files" },
  { id: "text-all", title: "All", path: "/text/all" },
  { id: "text-alt-codes", title: "Alt Codes", path: "/text/alt-codes" },
  { id: "text-ascii-table", title: "Ascii Table", path: "/text/ascii-table" },
  { id: "text-unicode-page", title: "Unicode Page", path: "/text/unicode-page" },
  { id: "electrical-calculations-amps-to-watts", title: "Amps To Watts", path: "/electrical-calculations/amps-to-watts" },
  { id: "electrical-calculations-watts-to-amps", title: "Watts To Amps", path: "/electrical-calculations/watts-to-amps" },
  { id: "electrical-calculations-ah-to-mah", title: "Ah To Mah", path: "/electrical-calculations/ah-to-mah" },
  { id: "electrical-calculations-amps-to-kilowatts", title: "Amps To Kilowatts", path: "/electrical-calculations/amps-to-kilowatts" },
  { id: "electrical-calculations-amps-to-kva", title: "Amps To Kva", path: "/electrical-calculations/amps-to-kva" },
  { id: "electrical-calculations-amps-to-kw", title: "Amps To Kw", path: "/electrical-calculations/amps-to-kw" },
  { id: "electrical-calculations-amps-to-milliamps", title: "Amps To Milliamps", path: "/electrical-calculations/amps-to-milliamps" },
  { id: "electrical-calculations-amps-to-ohms", title: "Amps To Ohms", path: "/electrical-calculations/amps-to-ohms" },
  { id: "electrical-calculations-amps-to-va", title: "Amps To Va", path: "/electrical-calculations/amps-to-va" },
  { id: "electrical-calculations-amps-to-volts", title: "Amps To Volts", path: "/electrical-calculations/amps-to-volts" },
  { id: "electrical-calculations-amp-to-watts", title: "Amp To Watts", path: "/electrical-calculations/amp-to-watts" },
  { id: "electrical-calculations-db-converter", title: "Db Converter Converter", path: "/electrical-calculations/db-converter" },
  { id: "electrical-calculations-electron-volt-to-volt", title: "Electron Volt To Volt", path: "/electrical-calculations/electron-volt-to-volt" },
  { id: "electrical-calculations-joules-to-kilowatts", title: "Joules To Kilowatts", path: "/electrical-calculations/joules-to-kilowatts" },
  { id: "electrical-calculations-joules-to-volts", title: "Joules To Volts", path: "/electrical-calculations/joules-to-volts" },
  { id: "electrical-calculations-joules-to-watts", title: "Joules To Watts", path: "/electrical-calculations/joules-to-watts" },
  { id: "electrical-calculations-kw-to-amps", title: "Kw To Amps", path: "/electrical-calculations/kw-to-amps" },
  { id: "electrical-calculations-kilowatts-to-joules", title: "Kilowatts To Joules", path: "/electrical-calculations/kilowatts-to-joules" },
  { id: "electrical-calculations-kilowatts-to-kva", title: "Kilowatts To Kva", path: "/electrical-calculations/kilowatts-to-kva" },
  { id: "electrical-calculations-kva-to-kw", title: "Kva To Kw", path: "/electrical-calculations/kva-to-kw" },
  { id: "electrical-calculations-kva-to-va", title: "Kva To Va", path: "/electrical-calculations/kva-to-va" },
  { id: "electrical-calculations-kw-to-kva", title: "Kw To Kva", path: "/electrical-calculations/kw-to-kva" },
  { id: "electrical-calculations-kw-to-joules", title: "Kw To Joules", path: "/electrical-calculations/kw-to-joules" },
  { id: "electrical-calculations-kva-to-amps", title: "Kva To Amps", path: "/electrical-calculations/kva-to-amps" },
  { id: "electrical-calculations-kva-to-watts", title: "Kva To Watts", path: "/electrical-calculations/kva-to-watts" },
  { id: "electrical-calculations-kwh-to-kw", title: "Kwh To Kw", path: "/electrical-calculations/kwh-to-kw" },
  { id: "electrical-calculations-kwh-to-watt", title: "Kwh To Watt", path: "/electrical-calculations/kwh-to-watt" },
  { id: "electrical-calculations-kw-to-kj", title: "Kw To Kj", path: "/electrical-calculations/kw-to-kj" },
  { id: "electrical-calculations-kw-to-kwh", title: "Kw To Kwh", path: "/electrical-calculations/kw-to-kwh" },
  { id: "electrical-calculations-kw-to-va", title: "Kw To Va", path: "/electrical-calculations/kw-to-va" },
  { id: "electrical-calculations-kw-to-volts", title: "Kw To Volts", path: "/electrical-calculations/kw-to-volts" },
  { id: "electrical-calculations-kw-to-wh", title: "Kw To Wh", path: "/electrical-calculations/kw-to-wh" },
  { id: "electrical-calculations-kw-to-watts", title: "Kw To Watts", path: "/electrical-calculations/kw-to-watts" },
  { id: "electrical-calculations-lumen-to-lux", title: "Lumen To Lux", path: "/electrical-calculations/lumen-to-lux" },
  { id: "electrical-calculations-lumen-to-watt", title: "Lumen To Watt", path: "/electrical-calculations/lumen-to-watt" },
  { id: "electrical-calculations-lux-to-lumen", title: "Lux To Lumen", path: "/electrical-calculations/lux-to-lumen" },
  { id: "electrical-calculations-mah-to-ah", title: "Mah To Ah", path: "/electrical-calculations/mah-to-ah" },
  { id: "electrical-calculations-mah-to-wh", title: "Mah To Wh", path: "/electrical-calculations/mah-to-wh" },
  { id: "electrical-calculations-milliamps-to-amps", title: "Milliamps To Amps", path: "/electrical-calculations/milliamps-to-amps" },
  { id: "electrical-calculations-ohms-to-amps", title: "Ohms To Amps", path: "/electrical-calculations/ohms-to-amps" },
  { id: "electrical-calculations-ohms-to-volts", title: "Ohms To Volts", path: "/electrical-calculations/ohms-to-volts" },
  { id: "electrical-calculations-vat-to-amps", title: "Vat To Amps", path: "/electrical-calculations/vat-to-amps" },
  { id: "electrical-calculations-vat-to-kva", title: "Vat To Kva", path: "/electrical-calculations/vat-to-kva" },
  { id: "electrical-calculations-vat-to-kw", title: "Vat To Kw", path: "/electrical-calculations/vat-to-kw" },
  { id: "electrical-calculations-vat-to-watts", title: "Vat To Watts", path: "/electrical-calculations/vat-to-watts" },
  { id: "electrical-calculations-volts-to-amps", title: "Volts To Amps", path: "/electrical-calculations/volts-to-amps" },
  { id: "electrical-calculations-volts-to-ev", title: "Volts To Ev", path: "/electrical-calculations/volts-to-ev" },
  { id: "electrical-calculations-volts-to-joules", title: "Volts To Joules", path: "/electrical-calculations/volts-to-joules" },
  { id: "electrical-calculations-volts-to-kw", title: "Volts To Kw", path: "/electrical-calculations/volts-to-kw" },
  { id: "electrical-calculations-volts-to-ohms", title: "Volts To Ohms", path: "/electrical-calculations/volts-to-ohms" },
  { id: "electrical-calculations-volts-to-watts", title: "Volts To Watts", path: "/electrical-calculations/volts-to-watts" },
  { id: "electrical-calculations-watts-to-kj", title: "Watts To Kj", path: "/electrical-calculations/watts-to-kj" },
  { id: "electrical-calculations-watts-to-kva", title: "Watts To Kva", path: "/electrical-calculations/watts-to-kva" },
  { id: "electrical-calculations-watts-to-kwh", title: "Watts To Kwh", path: "/electrical-calculations/watts-to-kwh" },
  { id: "electrical-calculations-watts-to-lumens", title: "Watts To Lumens", path: "/electrical-calculations/watts-to-lumens" },
  { id: "electrical-calculations-watts-to-va", title: "Watts To Va", path: "/electrical-calculations/watts-to-va" },
  { id: "electrical-calculations-watts-to-volts", title: "Watts To Volts", path: "/electrical-calculations/watts-to-volts" },
  { id: "electrical-calculations-watts-to-wh", title: "Watts To Wh", path: "/electrical-calculations/watts-to-wh" },
  { id: "electrical-calculations-wh-to-kw", title: "Wh To Kw", path: "/electrical-calculations/wh-to-kw" },
  { id: "electrical-calculations-wh-to-mah", title: "Wh To Mah", path: "/electrical-calculations/wh-to-mah" },
  { id: "electrical-calculations-wh-to-watts", title: "Wh To Watts", path: "/electrical-calculations/wh-to-watts" },
  { id: "electrical-calculations-watts-to-joules", title: "Watts To Joules", path: "/electrical-calculations/watts-to-joules" },
  { id: "wire-all", title: "All", path: "/wire/all" },
  { id: "time-all", title: "All", path: "/time/all" },
  { id: "math-all", title: "All", path: "/math/all" },
  { id: "grade-all", title: "All", path: "/grade/all" },
  { id: "calculator-college-gpa", title: "College Gpa GPA Calculator", path: "/calculator/college-gpa" },
  { id: "calculator-final-grade", title: "Final Grade Grade Calculator", path: "/calculator/final-grade" },
  { id: "calculator-gpa", title: "Gpa GPA Calculator", path: "/calculator/gpa" },
  { id: "calculator-grade-basic", title: "Grade Basic Grade Calculator", path: "/calculator/grade-basic" },
  { id: "calculator-gpa-calc", title: "Gpa Calc GPA Calculator", path: "/calculator/gpa-calc" },
  { id: "calculator-grade-calc", title: "Grade Calc Grade Calculator", path: "/calculator/grade-calc" },
  { id: "calculator-gpa-to-letter", title: "Gpa To Letter GPA Calculator", path: "/calculator/gpa-to-letter" },
  { id: "calculator-highschool-gpa", title: "Highschool Gpa GPA Calculator", path: "/calculator/highschool-gpa" },
  { id: "calculator-letter-to-gpa", title: "Letter To Gpa GPA Calculator", path: "/calculator/letter-to-gpa" },
  { id: "calculator-test", title: "Test Calculator", path: "/calculator/test" },
  { id: "ecology-all", title: "All", path: "/ecology/all" },
  { id: "image-conversions", title: "Image Conversions", path: "/image-conversions" },
  { id: "image-gif-to-png", title: "Gif  to  Png Tool", path: "/image/gif-to-png" },
  { id: "image-gif-to-jpg", title: "Gif  to  Jpg Tool", path: "/image/gif-to-jpg" },
  { id: "image-jpg-to-gif", title: "Jpg  to  Gif Tool", path: "/image/jpg-to-gif" },
  { id: "image-jpg-to-pdf", title: "Jpg  to  Pdf Tool", path: "/image/jpg-to-pdf" },
  { id: "image-jpg-to-png", title: "Jpg  to  Png Tool", path: "/image/jpg-to-png" },
  { id: "image-png-to-gif", title: "Png  to  Gif Tool", path: "/image/png-to-gif" },
  { id: "image-png-to-jpg", title: "Png  to  Jpg Tool", path: "/image/png-to-jpg" },
  { id: "image-png-to-pdf", title: "Png  to  Pdf Tool", path: "/image/png-to-pdf" },
  { id: "image-to-black-white", title: "to  Black White Tool", path: "/image/to-black-white" },
  { id: "word-counter", title: "Word Counter", path: "/word-counter" },
  { id: "character-counter", title: "Character Counter", path: "/character-counter" },
  { id: "line-counter", title: "Line Counter", path: "/line-counter" },
  { id: "word-frequency", title: "Word Frequency", path: "/word-frequency" },
  { id: "pdf-reader", title: "Pdf Reader", path: "/pdf-reader" },
  { id: "image-to-text", title: "Image  to  Text Tool", path: "/image-to-text" },
  { id: "image-to-pdf", title: "Image  to  Pdf Tool", path: "/image-to-pdf" },
  { id: "jpg-to-pdf", title: "Jpg To Pdf", path: "/jpg-to-pdf" },
  { id: "png-to-pdf", title: "Png To Pdf", path: "/png-to-pdf" },
  { id: "pdf-viewer", title: "Pdf Viewer", path: "/pdf-viewer" },
  { id: "current-time", title: "Current Time", path: "/current-time" },
  { id: "todays-date", title: "Todays Date", path: "/todays-date" },
  { id: "stopwatch", title: "Stopwatch", path: "/stopwatch" },
  { id: "alarm-clock", title: "Alarm Clock", path: "/alarm-clock" },
  { id: "todo-list", title: "Todo List", path: "/todo-list" },
  { id: "random-number", title: "Random Number", path: "/random-number" },
  { id: "bar-graph", title: "Bar Graph", path: "/bar-graph" },
  { id: "calendar", title: "Calendar", path: "/calendar" },
  { id: "call-recorder", title: "Call Recorder", path: "/call-recorder" },
  { id: "camera", title: "Camera", path: "/camera" },
  { id: "chart-maker", title: "Chart Maker", path: "/chart-maker" },
  { id: "click-counter", title: "Click Counter", path: "/click-counter" },
  { id: "cps-test", title: "Cps Test", path: "/cps-test" },
  { id: "countdown", title: "Countdown", path: "/countdown" },
  { id: "line-graph", title: "Line Graph", path: "/line-graph" },
  { id: "grocery-list", title: "Grocery List", path: "/grocery-list" },
  { id: "mic-test", title: "Mic Test", path: "/mic-test" },
  { id: "online-clock", title: "Online Clock", path: "/online-clock" },
  { id: "online-mirror", title: "Online Mirror", path: "/online-mirror" },
  { id: "notepad", title: "Notepad", path: "/notepad" },
  { id: "notes", title: "Notes", path: "/notes" },
  { id: "password-generator", title: "Password Generator", path: "/password-generator" },
  { id: "pie-chart", title: "Pie Chart", path: "/pie-chart" },
  { id: "scatter-plot", title: "Scatter Plot", path: "/scatter-plot" },
  { id: "scoreboard", title: "Scoreboard", path: "/scoreboard" },
  { id: "screen-recorder", title: "Screen Recorder", path: "/screen-recorder" },
  { id: "screenshot", title: "Screenshot", path: "/screenshot" },
  { id: "speech-to-text", title: "Speech To Text", path: "/speech-to-text" },
  { id: "text-editor", title: "Text Editor", path: "/text-editor" },
  { id: "table-chart", title: "Table Chart", path: "/table-chart" },
  { id: "text-to-speech", title: "Text To Speech", path: "/text-to-speech" },
  { id: "tone-generator", title: "Tone Generator", path: "/tone-generator" },
  { id: "ruler-cm", title: "Ruler Cm", path: "/ruler-cm" },
  { id: "ruler-inch", title: "Ruler Inch", path: "/ruler-inch" },
  { id: "voice-recorder", title: "Voice Recorder", path: "/voice-recorder" },
  { id: "webcam-test", title: "Webcam Test", path: "/webcam-test" },
  { id: "tools-redirect-generator", title: "Redirect Generator Tool", path: "/tools/redirect-generator" },
  { id: "tools-base64-encode", title: "Base64 Encode Tool", path: "/tools/base64-encode" },
  { id: "tools-base64-decode", title: "Base64 Decode Tool", path: "/tools/base64-decode" },
  { id: "tools-base64-to-image", title: "Base64 To Image Tool", path: "/tools/base64-to-image" },
  { id: "tools-image-to-base64", title: "Image To Base64 Tool", path: "/tools/image-to-base64" },
  { id: "tools-color-tester", title: "Color Tester Tool", path: "/tools/color-tester" },
  { id: "tools-color-picker-from-image", title: "Color Picker From Image Tool", path: "/tools/color-picker-from-image" },
  { id: "tools-html-editor", title: "Html Editor Tool", path: "/tools/html-editor" },
  { id: "tools-html-link-generator", title: "Html Link Generator Tool", path: "/tools/html-link-generator" },
  { id: "tools-html-table-generator", title: "Html Table Generator Tool", path: "/tools/html-table-generator" },
  { id: "tools-http-header-checker", title: "Http Header Checker Tool", path: "/tools/http-header-checker" },
  { id: "tools-http-status-checker", title: "Http Status Checker Tool", path: "/tools/http-status-checker" },
  { id: "tools-svg-viewer", title: "Svg Viewer Tool", path: "/tools/svg-viewer" },
  { id: "tools-url-encode", title: "Url Encode Tool", path: "/tools/url-encode" },
  { id: "tools-url-decode", title: "Url Decode Tool", path: "/tools/url-decode" },
  { id: "tools-screen-resolution", title: "Screen Resolution Tool", path: "/tools/screen-resolution" },
  { id: "tools-pixel-ruler", title: "Pixel Ruler Tool", path: "/tools/pixel-ruler" },
  { id: "tools-window-size", title: "Window Size Tool", path: "/tools/window-size" },

];

export const SearchBar = () => {
  const [open, setOpen] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");
  const [searchResults, setSearchResults] = useState<SearchResult[]>([]);
  const navigate = useNavigate();

  useEffect(() => {
    const down = (e: KeyboardEvent) => {
      if (e.key === "k" && (e.metaKey || e.ctrlKey)) {
        e.preventDefault();
        setOpen((open) => !open);
      }
    };
    document.addEventListener("keydown", down);
    return () => document.removeEventListener("keydown", down);
  }, []);

  useEffect(() => {
    const query = searchQuery.toLowerCase();
    const filtered = staticRoutes.filter(route =>
      route.title.toLowerCase().includes(query)
    );
    setSearchResults(filtered.slice(0, 10));
  }, [searchQuery]);

  const handleResultClick = (result: SearchResult) => {
    setOpen(false);
    navigate(result.path);
  };

  return (
    <>
      <Button 
        variant="outline" 
        className="relative h-9 w-full justify-start rounded-md text-sm text-muted-foreground sm:pr-12 md:w-40 lg:w-64"
        onClick={() => setOpen(true)}
      >
        <Search className="mr-2 h-4 w-4 shrink-0 opacity-50" />
        <span className="hidden lg:inline-flex">Search tools...</span>
        <span className="inline-flex lg:hidden">Search...</span>
        <kbd className="pointer-events-none absolute right-1.5 top-1.5 hidden h-5 select-none items-center gap-1 rounded border bg-muted px-1.5 font-mono text-[10px] font-medium opacity-100 sm:flex">
          <span className="text-xs">⌘</span>K
        </kbd>
      </Button>
      
      <CommandDialog open={open} onOpenChange={setOpen}>
        <CommandInput
          placeholder="Search tools..." 
          value={searchQuery}
          onValueChange={setSearchQuery}
        />
        <CommandList>
          <CommandEmpty>No results found</CommandEmpty>
          {searchResults.length > 0 && (
            <CommandGroup heading="Results">
              {searchResults.map((result) => (
                <CommandItem
                  key={result.id}
                  onSelect={() => handleResultClick(result)}
                >
                  {result.title}
                </CommandItem>
              ))}
            </CommandGroup>
          )}
        </CommandList>
      </CommandDialog>
    </>
  );
};
